### ISSUE TITLE
Please provide feature to add React component to highcharts tooltip

### ISSUE THREAD

**Issue by gokulb9993** [highcharts/highcharts-react#270] opened 2020-12-13 10:32 UTC

**Comment by ppotaczek** [comment] 2020-12-14 19:11
Hi @gokulb9993,

Duplicate of: https://github.com/highcharts/highcharts-react/issues/23

That is currently possible by using portals:  https://github.com/highcharts/highcharts-react#how-to-add-react-component-to-a-charts-element

**Closed by ppotaczek** 2020-12-14 19:11 UTC
