### ISSUE TITLE
Change chart type with scrollablePlotArea not working

### ISSUE THREAD

**Issue by victorhgoli** [highcharts/highcharts-react#274] opened 2020-12-30 23:11 UTC
Hi,  i need to change the type column to bar or bar to colum using scrollablePlotArea , but the axis of scroll doesnt change, when I change the state of component;
There is any way to solve this??
Follow the sample of problem

https://stackblitz.com/edit/react-xdyjki?file=index.js

**Comment by pawelfus** [comment] 2020-12-31 10:51
Hi @victorhgoli 

Thank you for reporting the issue. Changing series type from `column` to `bar`, or rather changing `chart.inverted` (which happens under the hood) is broken. This is already reported in #14758 - closing as a duplicate of #14758.

**Closed by pawelfus** 2020-12-31 10:51 UTC
