### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by qIsotope** [highcharts/highcharts-react#438] opened 2023-10-24 16:28 UTC
Hi, I'm trying to do a regression from react-highcharts to react-highcharts-official, and I want to do it correctly.
Please tell me how best to update the chart in my case.

tried to reproduce https://codesandbox.io/s/highcharts-react-demo-forked-r36ydq?file=/demo.jsx

The basic idea is that I get the series from API -> redux -> component, I tried to emulate this with setTimeout, but I'm not sure if it's right. And when I change the seriesTimeInterval, I make a new request to the API.

P.S. with immutable prop it looks correct, but only in this case of codesandbox, in my prod I have more props and I don't need to recreate the chart when changing them, only when changing seriesTimeInterval and series

**Comment by ppotaczek** [comment] 2023-10-25 15:28
Hi @qIsotope,

Thank you for contacting us!

Your code looks fine in general, you need to only disable the `chart.allowMutatingData` option.

    chart: {
      ...,
      allowMutatingData: false
    }

**API Reference:** https://api.highcharts.com/highcharts/chart.allowMutatingData

However, you can improve the updating process a bit by keeping chart options in a state and updating only the changed ones. 

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-j9s44p?file=/chart2.jsx
**Docs:** https://github.com/highcharts/highcharts-react#optimal-way-to-update

Best regards!

**Comment by qIsotope** [comment] 2023-10-25 15:40
@ppotaczek thanks a lot for reply!

i see one issue in your demo - https://codesandbox.io/s/highcharts-react-demo-j9s44p?file=/chart2.jsx

on first render i see xAxis label format in "daily" interval like "1 Jun", number of day and a month, when i change it to "weekly" and change again to "daily" i see only a number

**Comment by qIsotope** [comment] 2023-10-25 18:44
@ppotaczek moreover it breaks only when you pick "weekly", if pick "monthly" and return 'daily' it will not break

**Comment by ppotaczek** [comment] 2023-10-26 10:21
@qIsotope, that's because we need to reset the `formatter` function:

      xAxis = {
        labels: {
          formatter: null
        },
        ...
      };
      
**Live example:** https://codesandbox.io/s/highcharts-react-demo-tpp4t7?file=/chart2.jsx

**Comment by qIsotope** [comment] 2023-10-26 17:33
@ppotaczek thanks a lot!

i have another one strange issue only in one place in my app with this component that i used in demo, when i pick so many data, on first render with 'daily' interval all is okay, after i change on weekly or monthly and then 'daily' again some sAxis labels dissappears, and after i add some data it appears, maybe you know what can help with this. 
When I add immutable prop all works as expected...
[demo](https://github.com/highcharts/highcharts-react/assets/102731964/90eed227-4804-4028-ba5d-65b0cf617a61)

**Comment by ppotaczek** [comment] 2023-10-27 08:41
@qIsotope, Could you reproduce the problem in codesandbox? It seems that there are two updates when you change data.

**Comment by qIsotope** [comment] 2023-10-27 09:30
@ppotaczek https://codesandbox.io/s/highcharts-react-demo-forked-r36ydq?file=/demo.jsx here is.
important thing is to increase a width of window with component, component width should be 965px +-, this size in my app, and i add a button rerender to just rerender component,after click on this all xAxis appears
[demo.webm](https://github.com/highcharts/highcharts-react/assets/102731964/5abd0c9d-1d0d-4652-b5a7-dc663a1a4ddb)

**Comment by ppotaczek** [comment] 2023-10-27 10:54
@qIsotope, Maybe you could use functional component and React hooks, as in my provided example? In your example, series and x-axis are updated separately.

**Comment by qIsotope** [comment] 2023-10-31 14:42
@ppotaczek i tried but have issue when chart have multiple axes. 
example - https://codesandbox.io/s/highcharts-react-demo-forked-klrvkm?file=/chart2.jsx   
For reproduce you need press the overall and clean checkbox and then remove responses, it make area instead line for some reason

**Comment by ppotaczek** [comment] 2023-11-06 11:01
@qIsotope, That's because `yAxis` and `type` properties are defined only in one series. During update, series options are merged and this leads to an unwanted effect. To solve the problem, set the properties for all series. 

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-r295rj?file=/data.js

**Comment by qIsotope** [comment] 2023-11-21 11:37
@ppotaczek maybe you can help
after click on make rerender button charts yAxis changes for some reason
https://codesandbox.io/s/highcharts-react-demo-forked-j7hjdq?file=/demo.jsx

**Closed** 2023-11-21 12:24 UTC
Labels: question

**Comment by qIsotope** [comment] 2023-11-21 12:27
@ppotaczek This is what it looks like for me 

https://github.com/highcharts/highcharts-react/assets/102731964/626630a8-3436-454d-8fed-9b507b5fba27

**Comment by qIsotope** [comment] 2023-11-22 00:59
@ppotaczek its problem happens only in wrapper, not in vanila highcharts.js

**Comment by ppotaczek** [comment] 2023-11-22 10:24
@qIsotope, that's because the `yAxisParams` props are always new objects during rerenders. To avoid that, you can keep them in states or cache them by using `useMemo`.

```
  const [yAxisParams1] = useState({
    labelFormatter: (value) => value,
    maxValue: 100,
    plotLines: [
      {
        color: "#C8C8C8",
        value: 0,
        width: 2
      }
    ],
    tickInterval: 10
  });
  const [yAxisParams2] = useState({});
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forked-v6hdv9
