### ISSUE TITLE
Treemap charts lose color (display blank)

### ISSUE THREAD

**Issue by WeishengHong** [highcharts/highcharts-react#164] opened 2019-10-02 14:09 UTC
Hi, I am trying to use a packed bubble chart on my application, so I updated my highchart version to 7.2.0 and my highcharts-react-official is at version 2.2.2(latest). After I upgrade the highchart version, I found my existing treemap charts become blank. Any ideas? Below are my code. Thanks in advance.

```
import addTreemapModule from 'highcharts/modules/treemap';
import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts';

addTreemapModule(Highcharts);
const treeMapConfig = {// config object here};
<HighchartsReact
    highcharts={Highcharts}
   constructorType="chart"
   options={treeMapConfig}
/>
```

Version:
```
"react": "^16.8.0",
"highcharts": "7.2.0",
"highcharts-react-official": "2.2.2",
```

**Comment by ppotaczek** [comment] 2019-10-03 08:04
Hi @WeishengHong,

Thank you for contacting us!

Could you reproduce that problem in some online code editor? 
Here: https://codesandbox.io/s/highcharts-react-demo-t5bzb everything seems to be working properly.

Best regards!

**Comment by WeishengHong** [comment] 2019-10-03 20:32
Thanks for your reply. Unfortunately, looks like I can't reproduce the bug on the link you give me. But I can provide more information here.
<img width="1286" alt="Screen Shot 2019-10-03 at 4 29 37 PM" src="https://user-images.githubusercontent.com/38759161/66161866-388fa200-e5fb-11e9-9770-4d197174d958.png">

If you check the above image, the split bubble chart works but the tree map chart lost colors (I use the exactly same tree chart option object on your example).
<img width="1243" alt="Screen Shot 2019-10-03 at 4 31 09 PM" src="https://user-images.githubusercontent.com/38759161/66161937-51985300-e5fb-11e9-9ac6-fe0a3b2b8696.png">

And If I downgrade my highchart to 7.0.3, the tree map chart comes back, but the bubble chart is not split. I think the spilt bubble chart only works under 7.2.0, but in that version, the tree chart doesn't work. Do you have any ideas?

Hope this information helps.

**Comment by ppotaczek** [comment] 2019-10-04 10:05
Hi @WeishengHong,

Thank you for providing more information. 

That problem seems to be a duplicate of: https://github.com/highcharts/highcharts/issues/11738. Could you try to use some of the workarounds?

Best regards!

**Comment by ppotaczek** [comment] 2019-11-02 15:11
Closed due to inactivity.

**Closed by ppotaczek** 2019-11-02 15:11 UTC
Labels: pending reply
