### ISSUE TITLE
Provided tests with this repository are failing

### ISSUE THREAD

**Issue by ke4** [highcharts/highcharts-react#384] opened 2022-10-17 16:22 UTC
Hi,

I just cloned this repository and executed the tests as instructed: `npm run test`.
8 tests out of 20 are failing.

```
Test Suites: 6 failed, 5 passed, 11 total
Tests:       8 failed, 12 passed, 20 total
Snapshots:   0 total
Time:        9.596s
Ran all test suites.
```

Here is my local environment configuration.

```shell
$node --version
v16.15.0
$npm --version
8.5.5
$npm view react version
18.2.0
$npm view highcharts version
10.2.1
```

Here are some example of the error logs of the test execution:

```shell
  console.error
      Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'length')]
          at reportException (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
          at innerInvokeEventListeners (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
          at invokeEventListeners (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
          at HTMLUnknownElementImpl._dispatch (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
          at HTMLUnknownElement.dispatchEvent (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
          at Object.invokeGuardedCallbackDev (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:237:16)
          at invokeGuardedCallback (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:292:31)
          at commitRootImpl (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:22541:9)
          at unstable_runWithPriority (/Users/karoly/dev/study/react/highcharts-react/node_modules/scheduler/cjs/scheduler.development.js:653:12)
          at runWithPriority$1 (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
          at commitRoot (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:22381:3)
          at finishSyncRender (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:21807:3)
          at performSyncWorkOnRoot (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:21793:7)
          at /Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11089:24
          at unstable_runWithPriority (/Users/karoly/dev/study/react/highcharts-react/node_modules/scheduler/cjs/scheduler.development.js:653:12)
          at runWithPriority$1 (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
          at flushSyncCallbackQueueImpl (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11084:7)
          at flushSyncCallbackQueue (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11072:3)
          at scheduleUpdateOnFiber (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:21199:9)
          at Object.enqueueSetState (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:12639:5)
          at ParentComponent.setState (/Users/karoly/dev/study/react/highcharts-react/node_modules/react/cjs/react.development.js:471:16)
          at ReactWrapper.setState (/Users/karoly/dev/study/react/highcharts-react/node_modules/enzyme/src/ReactWrapper.js:377:21)
          at Object.<anonymous> (/Users/karoly/dev/study/react/highcharts-react/tests/__tests__/component/dynamics.test.js:37:13)
          at Object.asyncJestTest (/Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
          at /Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/queueRunner.js:45:12
          at new Promise (<anonymous>)
          at mapper (/Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
          at /Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/queueRunner.js:75:41
          at processTicksAndRejections (node:internal/process/task_queues:96:5) TypeError: Cannot read properties of undefined (reading 'length')
          at a.setTickPositions (/Users/karoly/dev/study/react/highcharts-react/node_modules/highcharts/highcharts.src.js:20284:25)
          at a.setTickInterval (/Users/karoly/dev/study/react/highcharts-react/node_modules/highcharts/highcharts.src.js:20188:17)
          at a.setScale (/Users/karoly/dev/study/react/highcharts-react/node_modules/highcharts/highcharts.src.js:20661:21)
          at forEach (/Users/karoly/dev/study/react/highcharts-react/node_modules/highcharts/highcharts.src.js:30832:21)
          at Array.forEach (<anonymous>)
          at a.redraw (/Users/karoly/dev/study/react/highcharts-react/node_modules/highcharts/highcharts.src.js:30830:17)
          at a.update (/Users/karoly/dev/study/react/highcharts-react/node_modules/highcharts/highcharts.src.js:32871:21)
          at /Users/karoly/dev/study/react/highcharts-react/src/HighchartsReact.js:56:36
          at commitHookEffectListMount (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:19731:26)
          at commitLifeCycles (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:19787:9)
          at commitLayoutEffects (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:22803:7)
          at HTMLUnknownElement.callCallback (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:188:14)
          at innerInvokeEventListeners (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
          at invokeEventListeners (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
          at HTMLUnknownElementImpl._dispatch (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
          at HTMLUnknownElement.dispatchEvent (/Users/karoly/dev/study/react/highcharts-react/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
          at Object.invokeGuardedCallbackDev (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:237:16)
          at invokeGuardedCallback (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:292:31)
          at commitRootImpl (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:22541:9)
          at unstable_runWithPriority (/Users/karoly/dev/study/react/highcharts-react/node_modules/scheduler/cjs/scheduler.development.js:653:12)
          at runWithPriority$1 (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
          at commitRoot (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:22381:3)
          at finishSyncRender (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:21807:3)
          at performSyncWorkOnRoot (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:21793:7)
          at /Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11089:24
          at unstable_runWithPriority (/Users/karoly/dev/study/react/highcharts-react/node_modules/scheduler/cjs/scheduler.development.js:653:12)
          at runWithPriority$1 (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
          at flushSyncCallbackQueueImpl (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11084:7)
          at flushSyncCallbackQueue (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:11072:3)
          at scheduleUpdateOnFiber (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:21199:9)
          at Object.enqueueSetState (/Users/karoly/dev/study/react/highcharts-react/node_modules/react-dom/cjs/react-dom.development.js:12639:5)
          at ParentComponent.setState (/Users/karoly/dev/study/react/highcharts-react/node_modules/react/cjs/react.development.js:471:16)
          at ReactWrapper.setState (/Users/karoly/dev/study/react/highcharts-react/node_modules/enzyme/src/ReactWrapper.js:377:21)
          at Object.<anonymous> (/Users/karoly/dev/study/react/highcharts-react/tests/__tests__/component/dynamics.test.js:37:13)
          at Object.asyncJestTest (/Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
          at /Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/queueRunner.js:45:12
          at new Promise (<anonymous>)
          at mapper (/Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
          at /Users/karoly/dev/study/react/highcharts-react/node_modules/jest-jasmine2/build/queueRunner.js:75:41
          at processTicksAndRejections (node:internal/process/task_queues:96:5)

      35 |
      36 |   it('Test function should be triggered - chart has been updated.', () => {
    > 37 |     wrapper.setState({
         |             ^
      38 |       options: {
      39 |         series: [{
      40 |           data: [1, 2, 3, 4]

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22541:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11089:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11084:7)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11072:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21199:9)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12639:5)
      at ParentComponent.setState (node_modules/react/cjs/react.development.js:471:16)
      at ReactWrapper.setState (node_modules/enzyme/src/ReactWrapper.js:377:21)
      at Object.<anonymous> (tests/__tests__/component/dynamics.test.js:37:13)

    console.error
      The above error occurred in the <ForwardRef(HighchartsReact)> component:
          in ForwardRef(HighchartsReact)
          in ForwardRef(HighchartsReact) (created by ParentComponent)
          in ParentComponent (created by WrapperComponent)
          in WrapperComponent
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

      35 |
      36 |   it('Test function should be triggered - chart has been updated.', () => {
    > 37 |     wrapper.setState({
         |             ^
      38 |       options: {
      39 |         series: [{
      40 |           data: [1, 2, 3, 4]

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:19527:21)
      at logError (node_modules/react-dom/cjs/react-dom.development.js:19564:5)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:20708:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:12490:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:12511:9)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19883:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22541:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11089:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11084:7)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11072:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21199:9)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12639:5)
      at ParentComponent.setState (node_modules/react/cjs/react.development.js:471:16)
      at ReactWrapper.setState (node_modules/enzyme/src/ReactWrapper.js:377:21)
      at Object.<anonymous> (tests/__tests__/component/dynamics.test.js:37:13)

  ● Test - chart update and chart destroy. › Test function should be triggered - chart has been updated.

    TypeError: Cannot read properties of undefined (reading 'length')

      54 |         if (props.allowChartUpdate !== false) {
      55 |           if (!props.immutable && chartRef.current) {
    > 56 |             chartRef.current.update(
         |                                    ^
      57 |               props.options,
      58 |               ...(props.updateArgs || [true, true])
      59 |             );

      at a.setTickPositions (node_modules/highcharts/highcharts.src.js:20284:25)
      at a.setTickInterval (node_modules/highcharts/highcharts.src.js:20188:17)
      at a.setScale (node_modules/highcharts/highcharts.src.js:20661:21)
      at forEach (node_modules/highcharts/highcharts.src.js:30832:21)
          at Array.forEach (<anonymous>)
      at a.redraw (node_modules/highcharts/highcharts.src.js:30830:17)
      at a.update (node_modules/highcharts/highcharts.src.js:32871:21)
      at src/HighchartsReact.js:56:36
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:19731:26)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19787:9)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22541:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11089:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11084:7)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11072:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21199:9)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12639:5)
      at ParentComponent.setState (node_modules/react/cjs/react.development.js:471:16)
      at ReactWrapper.setState (node_modules/enzyme/src/ReactWrapper.js:377:21)
      at Object.<anonymous> (tests/__tests__/component/dynamics.test.js:37:13)

 FAIL  tests/__tests__/props/callback.test.js (7.336s)
```

Could you advise us please to fix this issue?

Many thanks

**Comment by ppotaczek** [comment] 2022-10-28 14:50
Hi @ke4,

Thank you for contacting us and sorry for the late reply.

This problem is a Highchats regression bug, it occurs since Highcharts v10.1.0 and it is already fixed on the master branch. As a workaround for now, you can use Highcharts version lower than 10.1 (for example 10.0.0).

Related issue: https://github.com/highcharts/highcharts/issues/17300

Best regards!

**Closed** 2022-11-23 13:46 UTC
