### ISSUE TITLE
App crashes when using Highcharts @8.1.1

### ISSUE THREAD

**Issue by Ardeshir81** [highcharts/highcharts-react#227] opened 2020-06-20 06:54 UTC
I use highcharts@8.0.0 and everything is ok.
I update it to 8.1.1 and it crashes. I get error:

> ReferenceError: Highcharts is not defined

![image](https://user-images.githubusercontent.com/5755214/85195509-536c8880-b2e8-11ea-9031-8c76a9a2aefc.png)

**Comment by pawelfus** [comment] 2020-06-22 07:41
Thanks for reporting the issue @Ardeshir81 

It's a duplicate of https://github.com/highcharts/highcharts/issues/13710

**Closed by pawelfus** 2020-06-22 07:41 UTC
