### ISSUE TITLE
Callback function and ref don't return the pie chart with empty series data

### ISSUE THREAD

**Issue by morozserge1st** [highcharts/highcharts-react#229] opened 2020-07-03 14:20 UTC
Hello team. 

Currently, I have problems with the pie chart with empty series data after upgrading from 8.1.0 to 8.1.2.
Callback function and ref don't return the pie chart with empty series data.

This is the demo:
https://codesandbox.io/s/highchart-error-hp3qg

Here are the working versions of libraries:
- "highcharts": "8.1.0",
- "highcharts-react-official": "^3.0.0"

Thank you so much!

**Comment by pawelfus** [comment] 2020-07-06 14:14
Sound like a duplicate of Highcharts core issue: https://github.com/highcharts/highcharts/issues/13710 - could you try workaround posted there and let us know the results? Thanks!

**Comment by ppotaczek** [comment] 2020-08-05 08:26
Closed due to inactivity.

**Closed by ppotaczek** 2020-08-05 08:26 UTC
