### ISSUE TITLE
is there a way to control bubble size in packed bubble chart ?

### ISSUE THREAD

**Issue by kartikinfy** [highcharts/highcharts-react#406] opened 2023-05-15 13:54 UTC
to get a specific view we have created 9 packed bubble in a 3x3 grid.
The way I understand it, within a graph the bubbles render with size relative to each other, but if a graph has only one bubble it takes up the entire space. is there a way to control bubble size in such cases ?

![image](https://github.com/highcharts/highcharts-react/assets/54834406/67d691bf-41fe-481b-85f1-4036dd73f6cc)
![image](https://github.com/highcharts/highcharts-react/assets/54834406/0f0b8f5c-1b56-4ba0-b5b7-ff2ceddcae0a)

**Comment by ppotaczek** [comment] 2023-05-15 13:56
Closing as a duplicate of https://github.com/highcharts/highcharts-react/issues/404

**Closed by ppotaczek** 2023-05-15 13:56 UTC
