### ISSUE TITLE
Ajax loaded chart not displaying the second time its rendered

### ISSUE THREAD

**Issue by niwsa** [highcharts/highcharts-react#70] opened 2018-11-13 11:03 UTC
I have the sandbox up at https://codesandbox.io/s/lyz469j5o9.

The charts are being rendered in `Dashboard` component
```
 {items.map((item, index) => {
          let { i, chartType, ...dataGrid } = item;
          return (
            <div key={i} data-grid={{ ...dataGrid }}>
              <Chart
                resize={tainted === i || tainted === "all"}
                resizeDone={this.resizeChartDone}
                chartType={chartType}
              />
            </div>
          );
        })}
```
Inside the ```Chart``` component I am switching the chart based on ```chartType``` props passed from Dashboard.

All charts except the AJAX loaded one (charts/AjaxChartClickable.js) renders twice.I am initing the data module inside `Chart` for the ajax chart.

**UPDATE**: Taking cue from [highcharts#7729](https://github.com/highcharts/highcharts/issues/7729#issuecomment-361229106) made an attempt at creating custom highchart file and include all the modules from there but for reasons unknown to me that process is failing for which filed an issue at  [highcharts-assembler#6](https://github.com/highcharts/highcharts-assembler/issues/6)

**Comment by KacperMadej** [comment] 2018-11-15 10:11
Hi @niwsa 

Thank you for reporting about the problem.

After checking the issue - this is a Highcharts bug (data module bug to be precise), so I have reported this here: https://github.com/highcharts/highcharts/issues/9413

As a workaround you could use a deep copy of chart options object when setting up a chart that uses data module - details about the problematic props in the linked issue.

I'll close this issue as a duplicate of linked issue.

**Closed by KacperMadej** 2018-11-15 10:11 UTC
