### ISSUE TITLE
Build breaking regression

### ISSUE THREAD

**Issue by ecnaidar** [highcharts/highcharts-react#133] opened 2019-06-07 13:47 UTC
While deploying building started crashing with error
react-scripts 3.0.1
Node v10.16.0
Yarn v1.15.2
```
Creating an optimized production build...
Failed to compile.
./node_modules/highcharts-react-official/dist/highcharts-react.min.js
Cannot find module: 'React'. Make sure this package is installed.
You can install this package by running: yarn add React.
```
There seems it seems that recent releases affect this. 
NOTE Build was going through on different machine so there is definetely something fishy going on.
Locking in 2.1.3 version fixed the build process.

**Comment by Denyllon** [comment] 2019-06-07 14:06
Hi @ecnaidar ,

Thank you for reporting the issue.
This issue is the duplicate of #132. The problem is solved since v2.2.2, please update your package.

Kind regards!

**Closed by Denyllon** 2019-06-07 14:06 UTC
